version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - app-net

volumes:
  db_data:

networks:
  app-net:
